### ISSUE TITLE
Unexpected changes to embedded Shortcodes in Editable area

### ISSUE THREAD

**Issue by paulhibbitts** [bleutzinn/grav-plugin-editable-contenttools#1]
Hi @bleutzinn 

I've been testing out the plugin with my Open Publishing Space project, and I think I've come across a possible issue.

I had several Shortcodes in the Markdown text within the editable text area, and saving seemed to have changed the Shortcode text making them invalid.

Luckily, I was on auto Git Sync so you can see the exact before and after🙂
https://github.com/paulhibbitts/test-grav-skeleton-open-publishing-space-site/commit/e2b3e94be3014a1f41e9ea15b516bcbd9f89e0bf

Please let me know if you have any questions or if I can help in other ways.

Thanks,
Paul
ps - I've also got Trilby Media's Image Captions Plugin installed https://github.com/trilbymedia/grav-plugin-image-captions (though the issue also happened with the first plain image embed too)

**Comment by bleutzinn** [comment]
I'm afraid that this behaviour is not a bug but a feature. One I do not like at all I must add.

The plugin uses the Shortcode Core plugin to process the content of an `[editable]` shortcode. This processing renders the Markdown to HTML through the corresponding Twig templates.
The resulting HTML is the content the ContentTools editor works with.

Edited content (HTML) is converted back to Markdown just before saving. There is no reverse Twig rendering.

The only workaround I see now is to wrap text only Markdown in `[editable]` shortcodes instead of larger regions with nested shortcodes.

I'll start thinking of a better solution.

**Comment by paulhibbitts** [comment]
Thanks @bleutzinn , your suggested workaround is helpful and I will try that right now.

Keep me posted on further thoughts, and happy to test anything to help too.

**Comment by paulhibbitts** [comment]
Ok, that worked with the page having five separate edit areas. This approach actually is fine, but my one request would be some sort of "automatic" name generation if no name is given, otherwise you must remember to give each and every item a unique area (as I found out one duplicate name causes Save issues).

Might something like this be possible?
```
[editable] 
[/editable]
```

Thanks very much,
Paul

**Comment by bleutzinn** [comment]
I agree that generating a name when processing an "anonymous" shortcode would be very elegant. However generating such names at runtime requires storage of those names somewhere between serving the page and processing the changes upon a save action. This is not trivial (for me).

Adding the editable shortcodes to the content and giving them a name is almost a one time action. Each shortcode name needs to be unique within the page only. There's nothing wrong with having `[editable name="first-block"]` in more than one page. Also instead of a meaningful or sequential name anything will do as long as the characters are a-zA-Z0-9 or - or _

While writing I'm starting to consider modifying the original page and inserting unique shortcode names if needed. It does however not feel right to do that. On the other hand one might say it's just preprocessing.

**Comment by bleutzinn** [comment]
Version 1.3.1 includes an 'auto shortcode naming' feature supporting "anonymous" shortcodes. You can insert as many of these as you want in a page:
```
[editable]
Wear **sunscreen**.
[/editable]
```
