### ISSUE TITLE
Adding the 'properties bar'

### ISSUE THREAD

**Issue by markusritschel** [bleutzinn/grav-plugin-editable-contenttools#5]
Maybe not an issue but rather a feature request: [*ContentTools*](http://getcontenttools.com) shows on their website a so called [properties bar](http://getcontenttools.com/getting-started#configure-styles), which you can use to easily apply classes, styles etc. to the selected element.
Would it be possible without too much effort to implement this in the Grav plugin?
Btw, I really like the tool. Thanks for making this a Grav plugin!

**Comment by bleutzinn** [comment]
That bar or 'inspector' is disabled on purpose. The reason is that I chose to keep close to Markdown. Though HTML elements like `span` are allowed in Markdown the back and forth conversion will still be of limited success. By enabling the bar users will assume anything is possible just like when content source is HTML.

Grav pivots around Markdown with it's advantages and disadvantages. And this one of the limitations.

If you like to experiment you can enable the bar by deleting these [lines](https://github.com/bleutzinn/grav-plugin-editable-contenttools/blob/master/templates/editor.js.twig#L49:L54).

To preserve HTML elements during the conversion from HTML to Markdown by Turndown you may have to add these in the same file a bit earlier ([L18-L19](https://github.com/bleutzinn/grav-plugin-editable-contenttools/blob/master/templates/editor.js.twig#L18:L19)).

**Comment by markusritschel** [comment]
Ok, thanks. I see your point. Thank you also for your suggestions. I'll check it out during the coming days.

**Comment by bleutzinn** [comment]
Closing due to no further activity.
