### ISSUE TITLE
Using with ACL groups

### ISSUE THREAD

**Issue by Sogl** [bleutzinn/grav-plugin-editable-contenttools#6]
Hello!

I want to create a website for documentation in a company like https://learn.getgrav.org
Features:
- All departments can see all pages
- One department can edit only own page from frontend (for example, users from design can only edit Design pages and subpages)
- Department can create new md-files on the fly from frontend
- Department can add images and files (word, excel, pdf etc) to the page

As a start I want to implement first two features with your plugin.
Using search, I can found something for ACL/RBAC system:
https://learn.getgrav.org/16/advanced/groups-and-permissions
https://learn.getgrav.org/16/cookbook/general-recipes#require-special-permissions-to-view-one-or-more-pages
https://discourse.getgrav.org/t/restrict-hide-pages-by-group/5097/2

For example:
```yaml
access:
    site.design: true
    site.frontendedit: true
```

 Is it compatible with your plugin?

**Comment by bleutzinn** [comment]
Maybe. If in your example the `access.site.design` allows access to the page at all then using `access.site.editable` instead of `access.site.frontendedit` will allow the page being edited.

If that is not possible then, no, it can not be done without some changes to the plugin I'm afraid.

My [Editable with SimpleMDE Plugin](https://github.com/bleutzinn/grav-plugin-editable-simplemde#per-user) has per group and user permissions. Please take a look.

I haven't used that in my Editable with ContentTools Plugin because I think it doesn't work exactly as it should and since nobody created an issue I don't think that feature is used at all.

**Comment by bleutzinn** [comment]
Closing dus to inactivity.
